Repository Team-Sopetit/Sopetit-iOS, pull requests merged in 2024-01, with the labels that each got.

#8 [Feat] #4 - 공용 바텀시트 구현
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Global/Literals/ColorLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/FontLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/BottomSheet/BottomSheetType.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/BottomSheet/BottomSheetViewController.swift
Labels: 🐰아라, ✨Feat, 🎨UI

#10 [Feat] #3 - 텝바컨트롤러 구현 (하단바)
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/TabBar/TabBarController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/TabBar/TabBarItem.swift
Labels: 🐻‍❄️우제, ✨Feat, 🎨UI

#15 [HotFix] #14 - BundleID 변경
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Global/Literals/FontLiterals.swift
Labels: 🐰아라, ⚒️Fix

#17 [HotFix] #16 - 프로젝트 파일 충돌 해결
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/StoryTellingScene/View/StoryTellingFirstView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/StoryTellingScene/ViewController/StoryTellingViewController.swift
Labels: 🐰아라, ⚒️Fix

#13 [Feat] 로그인 뷰 구현
  .gitignore
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Application/AppDelegate.swift
  Sopetit-iOS/Sopetit-iOS/Application/SceneDelegate.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Info.plist
  Sopetit-iOS/Sopetit-iOS/Presentation/Auth/LoginScene/View/LoginView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
Labels: 🐺태경, ✨Feat

#19 [Feat] #9 - 행복루틴 Empty View UI 구현 및 Custom NavigationBar 구현
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Application/SceneDelegate.swift
  Sopetit-iOS/Sopetit-iOS/Global/Extension/UILabel+.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/ImageLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_chevron_back.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_chevron_back.imageset/ic_chevron_back.svg
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/svg_speech_long.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/svg_speech_long.imageset/svg_speech_long 1.svg
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/svg_speech_long.imageset/svg_speech_long 2.svg
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/svg_speech_long.imageset/svg_speech_long.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/svg_speech_long.imageset/svg_speech_long.svg
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/svg_speech_long.imageset/svg_speech_long@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/svg_speech_long.imageset/svg_speech_long@3x.png
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/TabBar/TabBarController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/Cell/HappyRoutineCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/View/BearDescriptionView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/View/HappyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/ViewController/HappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/NavigationBar/CustomNavigationBarView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/StoryTellingScene/View/StoryTellingFirstView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/StoryTellingScene/ViewController/StoryTellingViewController.swift
Labels: 😸민주, ✨Feat, 🎨UI

#21 [Feat] #18 - 온보딩 스토리텔링 뷰 구현
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Global/Extension/UILabel+.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/ViewController/HappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/StoryTellingScene/ViewController/StoryTellingViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/StroyTellingScene/View/StoryTellingSecondView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/StroyTellingScene/View/StoryTellingThirdView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/StroyTellingScene/View/StroyTellingFirstView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/StroyTellingScene/ViewController/StroyTellingViewController.swift
Labels: 🐰아라, ✨Feat, 🎨UI

#24 [Feat] #22 - 애착인형 선택 뷰 구현
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/CustomProgress/CustomProgressView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/DollChoiceScene/Cell/DollChoiceCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/DollChoiceScene/View/DollChoiceView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/DollChoiceScene/ViewController/DollChoiceViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/StroyTellingScene/View/StoryTellingSecondView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/StroyTellingScene/View/StoryTellingThirdView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/StroyTellingScene/View/StroyTellingFirstView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/StroyTellingScene/ViewController/StroyTellingViewController.swift
Labels: 🐰아라, ✨Feat, 🎨UI

#28 [Feat] #27 - 온보딩 루틴선택 뷰 구현
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Onboarding/RoutineChoiceEntity.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/Cell/RoutineChoiceCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/View/RoutineChoiceView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/ViewController/RoutineChoiceViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/ThemeSelectScene/ViewController/ThemeSelectViewController.swift
Labels: 🐰아라, ✨Feat, 🎨UI

#31 [Feat] #20 - 행복루틴 추가 뷰 UI 구현
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Global/Literals/ImageLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_happy_blue.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_happy_blue.imageset/ic_happy_blue.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_happy_blue.imageset/ic_happy_blue@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_happy_blue.imageset/ic_happy_blue@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_happy_green.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_happy_green.imageset/ic_happy_green.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_happy_green.imageset/ic_happy_green@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_happy_green.imageset/ic_happy_green@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_happy_orange.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_happy_orange.imageset/ic_happy_orange.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_happy_orange.imageset/ic_happy_orange@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_happy_orange.imageset/ic_happy_orange@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_happy_purple.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_happy_purple.imageset/ic_happy_purple.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_happy_purple.imageset/ic_happy_purple@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_happy_purple.imageset/ic_happy_purple@3x.png
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/Cell/HappyRoutineCardCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/Model/HappyRoutine.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/View/AddHappyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/ViewController/AddHappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/View/BearDescriptionView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/View/HappyRoutineEmptyView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/ViewController/HappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/NavigationBar/CustomNavigationBarView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/Cell/HappyRoutineCategoryCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/Cell/HappyRoutineTagCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/Model/HappyRoutineCategory.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/Model/HappyRoutineTag.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/View/HappyRoutineTagView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/View/SelectHappyCategoryView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/ViewController/SelectHappyCategoryViewController.swift
Labels: 😸민주, ✨Feat, 🎨UI

#33 [Feat] #32 - 행복루틴 메인 뷰 UI 구현
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Global/Literals/ImageLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_speech_happy.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_speech_happy.imageset/img_speech_happy.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_speech_happy.imageset/img_speech_happy@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_speech_happy.imageset/img_speech_happy@3x.png
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/BottomCTAButton/BottomCTAButton.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/Model/HappyRoutineCard.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/View/HappyRoutineCardView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/View/HappyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/ViewController/HappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/NavigationBar/CustomNavigationBarView.swift
Labels: 😸민주, ✨Feat, 🎨UI

#36 [Feat] #12 - 데일리루틴뷰 구현
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_add.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_add.imageset/ic_add.svg
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Routine/Daily/DailyEntity.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/TabBar/TabBarController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/Cell/DailyRoutineCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/View/DailyFooterView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/View/DailyView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/ViewController/DailyViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/NavigationBar/CustomNavigationBarView.swift
Labels: 🐻‍❄️우제, ✨Feat, 🎨UI

#39 [Feat] #37 - 바텀시트 수정사항 반영 및 연결, 토스트 메세지 구현
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Global/Literals/ImageLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_face_crying.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_face_crying.imageset/img_face_crying 1.svg
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_face_crying.imageset/img_face_crying 2.svg
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_face_crying.imageset/img_face_crying.svg
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Lottie/daily_complete_som.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Lottie/happy_complete_som.json
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/AlertMessage/AlertMessageView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/BottomSheet/BottomSheetType.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/BottomSheet/BottomSheetViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/TabBar/TabBarController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/Cell/DailyRoutineCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/ViewController/DailyViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/View/HappyRoutineCardView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/View/HappyRoutineEmptyView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/View/HappyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/ViewController/HappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/ViewController/RoutineChoiceViewController.swift
Labels: 🐰아라, ✨Feat, 🎨UI

#34 [Feat] #23 - 홈 뷰 구현
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Application/SceneDelegate.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/ImageLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_all_brown.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_all_brown.imageset/img_homeback_all_brown.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_all_brown.imageset/img_homeback_all_brown@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_all_brown.imageset/img_homeback_all_brown@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_all_gray.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_all_gray.imageset/img_homeback_all_gray.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_all_gray.imageset/img_homeback_all_gray@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_all_gray.imageset/img_homeback_all_gray@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_all_panda.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_all_panda.imageset/img_homeback_all_panda.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_all_panda.imageset/img_homeback_all_panda@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_all_panda.imageset/img_homeback_all_panda@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_all_red.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_all_red.imageset/img_homeback_all_red.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_all_red.imageset/img_homeback_all_red@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_all_red.imageset/img_homeback_all_red@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_brown.imageset/img_homeback_brown.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_brown.imageset/img_homeback_brown@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_brown.imageset/img_homeback_brown@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_gray.imageset/img_homeback_gray.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_gray.imageset/img_homeback_gray@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_gray.imageset/img_homeback_gray@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_panda.imageset/img_homeback_panda.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_panda.imageset/img_homeback_panda@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_panda.imageset/img_homeback_panda@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_red.imageset/img_homeback_red.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_red.imageset/img_homeback_red@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_homeback_red.imageset/img_homeback_red@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/png_speech_home.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/png_speech_home.imageset/png_speech_home.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/png_speech_home.imageset/png_speech_home@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/png_speech_home.imageset/png_speech_home@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/svg_speech_home.imageset/svg_speech_home 1.svg
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/svg_speech_home.imageset/svg_speech_home 2.svg
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/svg_speech_home.imageset/svg_speech_home.svg
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Home/HomeEntity.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/Cell/ActionCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/View/HomeView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/ViewController/HomeViewController.swift
Labels: 🐺태경, ✨Feat, 🎨UI

#48 [Feat] #44 - 데일리 루틴 추가 뷰 UI 구현
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Application/SceneDelegate.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/ImageLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_10.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_10.imageset/img_dailycard_10.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_10.imageset/img_dailycard_10@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_10.imageset/img_dailycard_10@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_11.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_11.imageset/img_dailycard_11.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_11.imageset/img_dailycard_11@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_11.imageset/img_dailycard_11@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_12.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_12.imageset/img_dailycard_12.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_12.imageset/img_dailycard_12@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_12.imageset/img_dailycard_12@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_2.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_2.imageset/img_dailycard_2.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_2.imageset/img_dailycard_2@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_2.imageset/img_dailycard_2@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_3.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_3.imageset/img_dailycard_3.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_3.imageset/img_dailycard_3@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_3.imageset/img_dailycard_3@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_4.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_4.imageset/img_dailycard_4.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_4.imageset/img_dailycard_4@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_4.imageset/img_dailycard_4@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_5.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_5.imageset/img_dailycard_5.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_5.imageset/img_dailycard_5@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_5.imageset/img_dailycard_5@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_6.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_6.imageset/img_dailycard_6.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_6.imageset/img_dailycard_6@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_6.imageset/img_dailycard_6@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_7.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_7.imageset/img_dailycard_7.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_7.imageset/img_dailycard_7@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_7.imageset/img_dailycard_7@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_8.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_8.imageset/img_dailycard_8.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_8.imageset/img_dailycard_8@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_8.imageset/img_dailycard_8@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_9.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_9.imageset/img_dailycard_9.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_9.imageset/img_dailycard_9@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_9.imageset/img_dailycard_9@3x.png
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/Cell/DailyRoutineCardCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/Cell/DailyRoutineThemeCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/Model/DailyRoutineCard.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/Model/DailyRoutineTheme.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/View/AddDailyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/View/DailyRoutineThemeView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/ViewController/AddDailyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/ViewController/AddHappyRoutineViewController.swift
Labels: 😸민주, ✨Feat, 🎨UI

#46 [Feat] #42 - 온보딩 테마선택뷰 API 연결
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Global/Extension/UIImageView+.swift
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Lottie/Lottie.swift
  Sopetit-iOS/Sopetit-iOS/Network/Base/URLConstant.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Onboarding/DollImageEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Onboarding/ThemeSelectEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Services/HappyRoutineService.swift
  Sopetit-iOS/Sopetit-iOS/Network/Services/OnboardingService.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/TabBar/TabBarController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/DollNameScene/View/DollNameView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/DollNameScene/ViewController/DollNameViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/OnboardingScene/View/OnboardingView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/OnboardingScene/ViewController/OnboardingViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/ThemeSelectScene/Cell/ThemeSelectCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/ThemeSelectScene/View/ThemeSelectView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/ThemeSelectScene/ViewController/ThemeSelectViewController.swift
  Sopetit-iOS/Sopetit-iOS/ViewController.swift
Labels: 🐰아라, ✨Feat, 🌎Network

#47 [Feat] #43 - 스플래시 화면 구현
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Application/SceneDelegate.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/ImageLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_logo_splash_1.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_logo_splash_1.imageset/ic_logo_splash_1.svg
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_logo_splash_2.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_logo_splash_2.imageset/ic_logo_splash_2.svg
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_splash_big_cut.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_splash_big_cut.imageset/img_splash_big_cut.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_splash_big_cut.imageset/img_splash_big_cut@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_splash_big_cut.imageset/img_splash_big_cut@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_splash_manybear_cut.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_splash_manybear_cut.imageset/img_splash_manybear_cut.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_splash_manybear_cut.imageset/img_splash_manybear_cut@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_splash_manybear_cut.imageset/img_splash_manybear_cut@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/splash_brown_sleeping.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/splash_brown_sleeping.imageset/splash_brown_sleeping.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/splash_brown_sleeping.imageset/splash_brown_sleeping@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/splash_brown_sleeping.imageset/splash_brown_sleeping@3x.png
  Sopetit-iOS/Sopetit-iOS/Info.plist
  Sopetit-iOS/Sopetit-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Splash/SplashScene/View/SplashFourView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Splash/SplashScene/View/SplashOneView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Splash/SplashScene/View/SplashThreeView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Splash/SplashScene/View/SplashTwoView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Splash/SplashScene/ViewController/SplashViewController.swift
Labels: 🐺태경, ✨Feat

#51 [Feat] #50 - 온보딩 루틴선택뷰 API 연결
  Sopetit-iOS/Sopetit-iOS/Network/Base/URLConstant.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Onboarding/RoutineChoiceEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Services/OnboardingService.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/Cell/RoutineChoiceCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/ViewController/RoutineChoiceViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/ThemeSelectScene/ViewController/ThemeSelectViewController.swift
Labels: 🐰아라, ✨Feat, 🌎Network

#53 [Feat] #52 - 바텀시트 추가 구현 및 연결
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/BottomSheet/BottomSheetType.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/BottomSheet/BottomSheetViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/NavigationBar/CustomNavigationBarView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/TabBar/TabBarController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/View/AddDailyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/ViewController/AddDailyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/View/DailyFooterView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/ViewController/DailyViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/View/AddHappyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/ViewController/AddHappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/View/HappyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/ViewController/HappyRoutineViewController.swift
Labels: 🐰아라, ✨Feat, 🎨UI

#45 [Feat] #38 - 설정뷰 UI 작업
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS.xcodeproj/xcshareddata/xcschemes/Sopetit-iOS.xcscheme
  Sopetit-iOS/Sopetit-iOS/Global/Extension/UILabel+.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/View/DailyView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/Cell/SettingTableViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/View/SettingView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/View/WithdrawView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/ViewController/SettingViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/ViewController/WithdrawViewController.swift
Labels: 🐻‍❄️우제, ✨Feat, 🎨UI

#60 [HotFix] #59 - 프로젝트 충돌 해결
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
Labels: 🐰아라, ⚒️Fix

#54 [Feat] #49 - 데일리루틴/행복루틴 완료 뷰 UI 구현 및 뒤로가기 로직 추가
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Application/SceneDelegate.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/ImageLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_bear_daily_complete_brown.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_bear_daily_complete_brown.imageset/img_bear_daily_complete_brown.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_bear_daily_complete_brown.imageset/img_bear_daily_complete_brown@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_bear_daily_complete_brown.imageset/img_bear_daily_complete_brown@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_bear_daily_complete_gray.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_bear_daily_complete_gray.imageset/img_bear_daily_complete_gray.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_bear_daily_complete_gray.imageset/img_bear_daily_complete_gray@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_bear_daily_complete_gray.imageset/img_bear_daily_complete_gray@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_bear_daily_complete_panda.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_bear_daily_complete_panda.imageset/img_bear_daily_complete_panda.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_bear_daily_complete_panda.imageset/img_bear_daily_complete_panda@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_bear_daily_complete_panda.imageset/img_bear_daily_complete_panda@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_bear_daily_complete_red.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_bear_daily_complete_red.imageset/img_bear_daily_complete_red.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_bear_daily_complete_red.imageset/img_bear_daily_complete_red@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_bear_daily_complete_red.imageset/img_bear_daily_complete_red@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_12 1.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_dailycard_12 1.imageset/img_dailycard_12@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_happy_bear_brown.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_happy_bear_brown.imageset/img_happy_bear_brown.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_happy_bear_brown.imageset/img_happy_bear_brown@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_happy_bear_brown.imageset/img_happy_bear_brown@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_happy_bear_gray.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_happy_bear_gray.imageset/img_happy_bear_gray.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_happy_bear_gray.imageset/img_happy_bear_gray@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_happy_bear_gray.imageset/img_happy_bear_gray@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_happy_bear_panda.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_happy_bear_panda.imageset/img_happy_bear_panda.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_happy_bear_panda.imageset/img_happy_bear_panda@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_happy_bear_panda.imageset/img_happy_bear_panda@3x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_happy_bear_red.imageset/Contents.json
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_happy_bear_red.imageset/img_happy_bear_red.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_happy_bear_red.imageset/img_happy_bear_red@2x.png
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/img_happy_bear_red.imageset/img_happy_bear_red@3x.png
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/NavigationBar/CustomNavigationBarView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/Cell/DailyRoutineThemeCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/View/AddDailyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/ViewController/AddDailyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/CompleteDailyRoutineScene/View/CompleteDailyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/CompleteDailyRoutineScene/ViewController/CompleteDailyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/ViewController/DailyViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/View/AddHappyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/ViewController/AddHappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/BottomCTAButton/BottomCTAButton.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/CompleteHappyRoutineScene/View/CompleteHappyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/CompleteHappyRoutineScene/ViewController/CompleteHappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/ViewController/HappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/View/SelectHappyCategoryView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/ViewController/SelectHappyCategoryViewController.swift
Labels: 😸민주, ✨Feat, 🎨UI

#61 [Feat] #57 - 온보딩뷰 멤버생성 API 연결
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Network/Base/URLConstant.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Onboarding/MemberEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Services/OnboardingService.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/DollChoiceScene/ViewController/DollChoiceViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/DollNameScene/ViewController/DollNameViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/View/RoutineChoiceView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/ViewController/RoutineChoiceViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/ThemeSelectScene/ViewController/ThemeSelectViewController.swift
Labels: 🐰아라, ✨Feat, 🌎Network

#63 [Feat] #56 - 카카오로그인 API 구현
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Application/Manager/User/UserManager.swift
  Sopetit-iOS/Sopetit-iOS/Network/Base/URLConstant.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Auth/Login/LoginEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Services/AuthService.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Auth/LoginScene/View/LoginView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Splash/SplashScene/ViewController/SplashViewController.swift
  Sopetit-iOS/Sopetit-iOS/Sopetit-iOS.entitlements
Labels: 🐺태경, ✨Feat, 🌎Network

#64 [Feat] #58 - 데일리루틴뷰 GET API 연결
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Global/Extension/UIImageView+.swift
  Sopetit-iOS/Sopetit-iOS/Network/Base/URLConstant.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Routine/Daily/DailyEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Routine/Daily/DailyRoutineEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Services/DailyRoutineService.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/Cell/DailyRoutineCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/ViewController/DailyViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/View/SettingView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/ViewController/SettingViewController.swift
Labels: 🐻‍❄️우제, ✨Feat, 🌎Network, 🎨UI

#68 [Feat] #66 - 온보딩뷰 레이아웃 수정
  Sopetit-iOS/Sopetit-iOS/Application/Manager/User/UserManager.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/CompleteDailyRoutineScene/View/CompleteDailyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/ViewController/HappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/View/HomeView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/DollNameScene/View/DollNameView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/View/RoutineChoiceView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/ViewController/RoutineChoiceViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/StroyTellingScene/View/StoryTellingSecondView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/StroyTellingScene/View/StoryTellingThirdView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/StroyTellingScene/View/StroyTellingFirstView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/ThemeSelectScene/ViewController/ThemeSelectViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Splash/SplashScene/ViewController/SplashViewController.swift
Labels: 🐰아라, 🎨Chore

#71 [Feat] #55 - 행복루틴 뷰 API 연결
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Global/Extension/UIView+.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Network/Base/URLConstant.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Routine/Happiness/HappinessEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Routine/Happiness/HappinessMemberEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Routine/Happiness/HappinessRoutineEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Routine/Happiness/HappinessRoutineIdEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Routine/Happiness/HappinessThemesEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Services/HappyRoutineService.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/BottomSheet/BottomSheetViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/ViewController/AddDailyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/Cell/HappyRoutineCardCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/Model/HappyRoutine.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/View/AddHappyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/ViewController/AddHappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/CompleteHappyRoutineScene/ViewController/CompleteHappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/Model/HappyRoutineCard.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/View/HappyRoutineCardView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/View/HappyRoutineEmptyView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/View/HappyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/ViewController/HappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/Cell/HappyRoutineCategoryCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/Model/HappyRoutineCategory.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/Model/HappyRoutineTag.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/ViewController/SelectHappyCategoryViewController.swift
Labels: 😸민주, ✨Feat, 🌎Network

#74 [Feat] #69 - 로그아웃/탈퇴 구현
  Sopetit-iOS/Sopetit-iOS/Application/Manager/User/UserManager.swift
  Sopetit-iOS/Sopetit-iOS/Network/Base/URLConstant.swift
  Sopetit-iOS/Sopetit-iOS/Network/Services/AuthService.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/ViewController/HomeViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/ViewController/SettingViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/ViewController/WithdrawViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Splash/SplashScene/ViewController/SplashViewController.swift
Labels: 🐺태경, ✨Feat, 🌎Network

#73 [Feat] #65 - 데일리루틴뷰 API 연결
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Network/Base/URLConstant.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Routine/Daily/DailyDeleteEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Routine/Daily/DailyPatchEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Routine/Daily/DailyRoutineEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Services/DailyRoutineService.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/Cell/DailyRoutineCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/View/DailyFooterView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/View/DailyView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/ViewController/DailyViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/ViewController/HomeViewController.swift
Labels: 🐻‍❄️우제, ✨Feat, 🌎Network, 🎨UI

#76 [Chore] #75 - 홈 뷰 데이터 불러오기 개선
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/View/HomeView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/ViewController/HomeViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/ViewController/WithdrawViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Splash/SplashScene/View/SplashFourView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Splash/SplashScene/View/SplashOneView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Splash/SplashScene/View/SplashThreeView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Splash/SplashScene/View/SplashTwoView.swift
Labels: 🐺태경, 🎨Chore, 🌎Network

#77 [Feat] #70 - 홈뷰 솜뭉치주기 API 연결
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Network/Base/URLConstant.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Home/HomeCottonEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Services/HomeService.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/Cell/ActionCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/View/HomeView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/ViewController/HomeViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/View/RoutineChoiceView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/ViewController/SettingViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/ViewController/WithdrawViewController.swift
Labels: 🐰아라, ✨Feat, 🌎Network

#78 [Feat] #72 - 데일리 루틴 추가 관련 API 연결 및 데일리루틴 로직 수정
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Network/Base/URLConstant.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Routine/Daily/DailyRoutineIdEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Routine/Daily/DailyRoutinesEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Routine/Daily/DailyThemesEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Services/AddDailyRoutineService.swift
  Sopetit-iOS/Sopetit-iOS/Network/Services/DailyRoutineService.swift
  Sopetit-iOS/Sopetit-iOS/Network/Services/HappyRoutineService.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/Cell/DailyRoutineCardCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/Cell/DailyRoutineThemeCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/View/AddDailyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/ViewController/AddDailyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/Cell/DailyRoutineCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/View/DailyView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/ViewController/DailyViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/ViewController/AddHappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/ViewController/HappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/ViewController/SelectHappyCategoryViewController.swift
Labels: 😸민주, ✨Feat, ⚒️Fix, 🌎Network, ♻️Refactor

#84 [Feat] #83 - 설정뷰 웹뷰 연결
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Info.plist
  Sopetit-iOS/Sopetit-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/View/WithdrawView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/ViewController/SettingViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/ViewController/WithdrawViewController.swift
Labels: 🐰아라, ✨Feat

#86 [Feat] #85 - 바텀시트뷰 바인딩 구현
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/BottomSheet/BottomSheetViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/ViewController/AddDailyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/ViewController/DailyViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/ViewController/AddHappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/ViewController/HappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/ViewController/SelectHappyCategoryViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/ViewController/HomeViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/View/RoutineChoiceView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/ThemeSelectScene/View/ThemeSelectView.swift
Labels: 🐰아라, ✨Feat

#89 [Fix] #87 - QA 반영
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Application/AppDelegate.swift
  Sopetit-iOS/Sopetit-iOS/Application/Manager/User/UserManager.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Onboarding/OnboardingEntity.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/NavigationBar/CustomNavigationBarView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/ViewController/AddDailyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/CompleteDailyRoutineScene/View/BearType.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/CompleteDailyRoutineScene/View/CompleteDailyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/CompleteDailyRoutineScene/ViewController/CompleteDailyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/Cell/DailyRoutineCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/ViewController/AddHappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/CompleteHappyRoutineScene/View/CompleteHappyRoutineView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/CompleteHappyRoutineScene/ViewController/CompleteHappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/View/BearDescriptionView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/ViewController/HappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/View/HomeView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/ViewController/HomeViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/DollChoiceScene/ViewController/DollChoiceViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/DollNameScene/View/DollNameView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/DollNameScene/ViewController/DollNameViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/View/RoutineChoiceView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/ViewController/RoutineChoiceViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/StroyTellingScene/ViewController/StroyTellingViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/ThemeSelectScene/ViewController/ThemeSelectViewController.swift
Labels: 🐰아라, ⚒️Fix

#93 [Fix] #92 - 아요 QA 반영
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS.xcodeproj/xcshareddata/xcschemes/Sopetit-iOS.xcscheme
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/logo.png
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/CompleteDailyRoutineScene/View/BearType.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/ViewController/HomeViewController.swift
Labels: 🐰아라, ⚒️Fix

#95 [Feat] #94 - API 수정
  Sopetit-iOS/Sopetit-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/Cell/DailyRoutineCardCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/ViewController/HomeViewController.swift
Labels: 🐰아라, ⚒️Fix

#97 [Fix] #96 - 홈뷰 로직 수정
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/ViewController/HappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/ViewController/HomeViewController.swift
Labels: 🐰아라, ⚒️Fix

#101 [FIx] #100 - 마지막 수정
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/Cell/DailyRoutineCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/ViewController/DailyViewController.swift
Labels: 🐰아라, ⚒️Fix

#107 [Feat] #106 - Refresh Token API 구현
  Sopetit-iOS/Sopetit-iOS/Application/Manager/User/UserManager.swift
  Sopetit-iOS/Sopetit-iOS/Network/Base/URLConstant.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Auth/Login/LoginEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Services/AuthService.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Splash/SplashScene/ViewController/SplashViewController.swift
Labels: ✨Feat, 🌎Network

#111 [Chore] #110 - 디자인 변경사항 반영 및 이슈 해결
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Global/Extension/UILabel+.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Network/Base/URLConstant.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Routine/Daily/DailyDeleteEntity.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/NavigationBar/CustomNavigationBarView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/ViewController/AddDailyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/Cell/HappyRoutineCardCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/ViewController/AddHappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/ViewController/SelectHappyCategoryViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/ThemeSelectScene/ViewController/ThemeSelectViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/ViewController/SettingViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/ViewController/WithdrawViewController.swift
Labels: 🐰아라, 🎨Chore

#112 [Chore] #108 - QA 반영
  Sopetit-iOS/Sopetit-iOS/Application/AppDelegate.swift
  Sopetit-iOS/Sopetit-iOS/Application/Manager/User/UserManager.swift
  Sopetit-iOS/Sopetit-iOS/Application/SceneDelegate.swift
  Sopetit-iOS/Sopetit-iOS/Info.plist
  Sopetit-iOS/Sopetit-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/ViewController/HomeViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/ViewController/RoutineChoiceViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/ViewController/SettingViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Splash/SplashScene/ViewController/SplashViewController.swift
Labels: 🐺태경, ✨Feat, 🎨Chore

#116 [Feat] #114 - 홈 뷰 로딩 구현
  Sopetit-iOS/Sopetit-iOS/Application/SceneDelegate.swift
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_home_money.imageset/ic_home_money 1.svg
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_home_money.imageset/ic_home_money 2.svg
  Sopetit-iOS/Sopetit-iOS/Global/Resources/Assets.xcassets/ic_home_money.imageset/ic_home_money.svg
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/View/HomeView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/ViewController/HomeViewController.swift
Labels: 🐺태경, ✨Feat, ⚒️Fix
