Repository Team-Sopetit/Sopetit-iOS, pull requests merged in 2024-02, with the labels that each got.

#122 [Fix] #121 - 데일리루틴 뷰 편집중일 때 완료하기 버튼 비활성화, 데일리루틴 뷰 두줄짜리 레이아웃 겹침 이슈 해결
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/Cell/DailyRoutineCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/ViewController/DailyRoutineViewController.swift
Labels: 😸민주, ⚒️Fix

#123 [Fix] #120 - Refresh Token 로직 수정
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS/Network/Base/BaseService.swift
  Sopetit-iOS/Sopetit-iOS/Network/Base/NetworkResult.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Auth/Login/LoginEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Services/AuthService.swift
  Sopetit-iOS/Sopetit-iOS/Network/Services/ReissueService.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/ViewController/AddDailyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/ViewController/DailyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/ViewController/AddHappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/ViewController/HappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/ViewController/SelectHappyCategoryViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/ViewController/HomeViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/ViewController/RoutineChoiceViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/ViewController/SettingViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/ViewController/WithdrawViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Splash/SplashScene/ViewController/SplashViewController.swift
Labels: 🐺태경, ⚒️Fix

#118 [Feat] #117 - 업데이트 뷰 구현 및 버전조회 API 연결
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS.xcodeproj/xcshareddata/xcschemes/Sopetit-iOS.xcscheme
  Sopetit-iOS/Sopetit-iOS/Application/AppDelegate.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/ColorLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Literals/StringLiterals.swift
  Sopetit-iOS/Sopetit-iOS/Global/Utils/MakeAlert.swift
  Sopetit-iOS/Sopetit-iOS/Network/Base/URLConstant.swift
  Sopetit-iOS/Sopetit-iOS/Network/Entity/Auth/Version/VersionEntity.swift
  Sopetit-iOS/Sopetit-iOS/Network/Services/AuthService.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Common/UpdateAlert/UpdateAlertView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/AddDailyRoutineScene/ViewController/AddDailyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/Cell/DailyRoutineCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/DailyRoutine/DailyRoutineScene/ViewController/DailyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/AddHappyRoutineScene/ViewController/AddHappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/View/HappyRoutineEmptyView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/HappyRoutineScene/ViewController/HappyRoutineViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/HappyRoutine/SelectHappyCategoryScene/ViewController/SelectHappyCategoryViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Home/HomeScene/ViewController/HomeViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/ViewController/RoutineChoiceViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/ThemeSelectScene/Cell/ThemeSelectCollectionViewCell.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/ThemeSelectScene/View/ThemeSelectView.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/ViewController/SettingViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Setting/SettingScene/ViewController/WithdrawViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Splash/SplashScene/ViewController/SplashViewController.swift
Labels: 🐰아라, ✨Feat, 🌎Network, 🎨UI

#125 [Feat] #124 - 릴리즈 전 수정사항 반영
  Sopetit-iOS/Sopetit-iOS.xcodeproj/project.pbxproj
  Sopetit-iOS/Sopetit-iOS.xcodeproj/xcshareddata/xcschemes/Sopetit-iOS.xcscheme
  Sopetit-iOS/Sopetit-iOS/Network/Services/OnboardingService.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Auth/LoginScene/ViewController/LoginViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/RoutineChoiceScene/ViewController/RoutineChoiceViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Onboarding/ThemeSelectScene/ViewController/ThemeSelectViewController.swift
  Sopetit-iOS/Sopetit-iOS/Presentation/Splash/SplashScene/ViewController/SplashViewController.swift
Labels: 🐰아라, ⚒️Fix
